[package]
name = "telnet-gateway-menu"
version = "0.1.0"
authors = ["Les Orchard <me@lmorchard.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
